### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by Bluemi** [curious-containers/curious-containers#77]
There are some problems with old dependencies.

- pyzmq does not build with newer python versions (>= 3.8)
- ImportError: cannot import name 'soft_unicode' from 'markupsafe', has to downgrade markupsafe==2.0.1

**Comment by Bluemi** [comment]
Fixed with release 9.1.1
